package zhrk.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("QX_BLOG", "ID", QxBlog.class);
		arp.addMapping("QX_CAMAREA", "ID", QxCamarea.class);
		arp.addMapping("QX_DISASTER", "ID", QxDisaster.class);
		arp.addMapping("QX_DIS_RESULT", "ID", QxDisResult.class);
		arp.addMapping("QX_DIS_USER", "ID", QxDisUser.class);
		arp.addMapping("QX_MENU", "ID", QxMenu.class);
		arp.addMapping("QX_MESSAGE", "ID", QxMessage.class);
		arp.addMapping("QX_MISSING", "ID", QxMissing.class);
		arp.addMapping("QX_PIC_LIBRARY", "ID", QxPicLibrary.class);
		arp.addMapping("QX_REC_MESSAGE", "ID", QxRecMessage.class);
		arp.addMapping("QX_RELA", "ID", QxRela.class);
		arp.addMapping("QX_ROLE", "ID", QxRole.class);
		arp.addMapping("QX_ROMENU", "ID", QxRomenu.class);
		arp.addMapping("QX_SEND", "ID", QxSend.class);
		arp.addMapping("QX_STAFF", "ID", QxStaff.class);
		arp.addMapping("QX_UR", "ID", QxUr.class);
		arp.addMapping("QX_USER", "ID", QxUser.class);
		arp.addMapping("QX_USER_LIBRARY", "ID", QxUserLibrary.class);
		arp.addMapping("QX_VIDEO_LIBRARY", "ID", QxVideoLibrary.class);
	}
}

