package zhrk.common.model;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import com.jfinal.plugin.activerecord.ActiveRecordException;
import com.jfinal.plugin.activerecord.Config;
import com.jfinal.plugin.activerecord.Table;

import zhrk.common.model.base.BaseQxUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QxUser extends BaseQxUser<QxUser> {

	public boolean save(Map<String, Object> attrs) {
		filter(FILTER_BY_SAVE);
		Config config = _getConfig();
		Table table = _getTable();
		StringBuilder sql = new StringBuilder();
		List<Object> paras = new ArrayList<Object>();
		config.getDialect().forModelSave(table, attrs, sql, paras);
		Connection conn = null;
		PreparedStatement pst = null;
		int result = 0;
		try {
			conn = config.getConnection();
			pst = conn.prepareStatement(sql.toString());
			config.getDialect().fillStatement(pst, paras);
			result = pst.executeUpdate();
			config.getDialect().getModelGeneratedKey(this, pst, table);
			_getModifyFlag().clear();
			return result >= 1;
		} catch (Exception e) {
			throw new ActiveRecordException(e);
		} finally {
			config.close(pst, conn);
		}
	}
}
