package zhrk.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQxMissing<M extends BaseQxMissing<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("ID", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public M setReuser(java.lang.Integer reuser) {
		set("REUSER", reuser);
		return (M)this;
	}
	
	public java.lang.Integer getReuser() {
		return getInt("REUSER");
	}

	public M setMiuser(java.lang.Integer miuser) {
		set("MIUSER", miuser);
		return (M)this;
	}
	
	public java.lang.Integer getMiuser() {
		return getInt("MIUSER");
	}

	public M setContent(java.lang.String content) {
		set("CONTENT", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("CONTENT");
	}

	public M setUserstate(java.lang.String userstate) {
		set("USERSTATE", userstate);
		return (M)this;
	}
	
	public java.lang.String getUserstate() {
		return getStr("USERSTATE");
	}

	public M setMisdate(java.util.Date misdate) {
		set("MISDATE", misdate);
		return (M)this;
	}
	
	public java.util.Date getMisdate() {
		return get("MISDATE");
	}

	public M setRegdate(java.util.Date regdate) {
		set("REGDATE", regdate);
		return (M)this;
	}
	
	public java.util.Date getRegdate() {
		return get("REGDATE");
	}

	public M setType(java.lang.String type) {
		set("TYPE", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("TYPE");
	}

	public M setInfstate(java.lang.String infstate) {
		set("INFSTATE", infstate);
		return (M)this;
	}
	
	public java.lang.String getInfstate() {
		return getStr("INFSTATE");
	}

	public M setPicpath(java.lang.String picpath) {
		set("PICPATH", picpath);
		return (M)this;
	}
	
	public java.lang.String getPicpath() {
		return getStr("PICPATH");
	}

	public M setAddress(java.lang.String address) {
		set("ADDRESS", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("ADDRESS");
	}

}
