package zhrk.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQxUser<M extends BaseQxUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("ID", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public M setName(java.lang.String name) {
		set("NAME", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("NAME");
	}

	public M setUsercode(java.lang.String usercode) {
		set("USERCODE", usercode);
		return (M)this;
	}
	
	public java.lang.String getUsercode() {
		return getStr("USERCODE");
	}

	public M setPwd(java.lang.String pwd) {
		set("PWD", pwd);
		return (M)this;
	}
	
	public java.lang.String getPwd() {
		return getStr("PWD");
	}

	public M setTel(java.lang.String tel) {
		set("TEL", tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("TEL");
	}

	public M setType(java.lang.String type) {
		set("TYPE", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("TYPE");
	}

	public M setIsvolun(java.lang.Integer isvolun) {
		set("ISVOLUN", isvolun);
		return (M)this;
	}
	
	public java.lang.Integer getIsvolun() {
		return getInt("ISVOLUN");
	}

	public M setStatus(java.lang.Integer status) {
		set("STATUS", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("STATUS");
	}

	public M setRemark(java.lang.String remark) {
		set("REMARK", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("REMARK");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("CREATETIME", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("CREATETIME");
	}

}
