package zhrk.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQxMessage<M extends BaseQxMessage<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("ID", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public M setMsid(java.lang.Integer msid) {
		set("MSID", msid);
		return (M)this;
	}
	
	public java.lang.Integer getMsid() {
		return getInt("MSID");
	}

	public M setTitle(java.lang.String title) {
		set("TITLE", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("TITLE");
	}

	public M setContent(java.lang.String content) {
		set("CONTENT", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("CONTENT");
	}

	public M setAddr(java.lang.String addr) {
		set("ADDR", addr);
		return (M)this;
	}
	
	public java.lang.String getAddr() {
		return getStr("ADDR");
	}

	public M setSendtime(java.util.Date sendtime) {
		set("SENDTIME", sendtime);
		return (M)this;
	}
	
	public java.util.Date getSendtime() {
		return get("SENDTIME");
	}

}
