package zhrk.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQxVideoLibrary<M extends BaseQxVideoLibrary<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("ID", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public M setCamid(java.lang.Integer camid) {
		set("CAMID", camid);
		return (M)this;
	}
	
	public java.lang.Integer getCamid() {
		return getInt("CAMID");
	}

	public M setVideopath(java.lang.String videopath) {
		set("VIDEOPATH", videopath);
		return (M)this;
	}
	
	public java.lang.String getVideopath() {
		return getStr("VIDEOPATH");
	}

	public M setStarttime(java.util.Date starttime) {
		set("STARTTIME", starttime);
		return (M)this;
	}
	
	public java.util.Date getStarttime() {
		return get("STARTTIME");
	}

	public M setEndtime(java.util.Date endtime) {
		set("ENDTIME", endtime);
		return (M)this;
	}
	
	public java.util.Date getEndtime() {
		return get("ENDTIME");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("CREATETIME", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("CREATETIME");
	}

}
