package zhrk.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQxBlog<M extends BaseQxBlog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("ID", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public M setTitle(java.lang.String title) {
		set("TITLE", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("TITLE");
	}

	public M setContent(java.lang.String content) {
		set("CONTENT", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("CONTENT");
	}

}
