package zhrk.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQxDisResult<M extends BaseQxDisResult<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("ID", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public M setUsercode(java.lang.String usercode) {
		set("USERCODE", usercode);
		return (M)this;
	}
	
	public java.lang.String getUsercode() {
		return getStr("USERCODE");
	}

	public M setPicture(java.lang.String picture) {
		set("PICTURE", picture);
		return (M)this;
	}
	
	public java.lang.String getPicture() {
		return getStr("PICTURE");
	}

	public M setScore(java.lang.String score) {
		set("SCORE", score);
		return (M)this;
	}
	
	public java.lang.String getScore() {
		return getStr("SCORE");
	}

	public M setDisid(java.lang.Integer disid) {
		set("DISID", disid);
		return (M)this;
	}
	
	public java.lang.Integer getDisid() {
		return getInt("DISID");
	}

}
