package zhrk.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQxUserLibrary<M extends BaseQxUserLibrary<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("ID", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public M setName(java.lang.String name) {
		set("NAME", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("NAME");
	}

	public M setUsercode(java.lang.String usercode) {
		set("USERCODE", usercode);
		return (M)this;
	}
	
	public java.lang.String getUsercode() {
		return getStr("USERCODE");
	}

	public M setSex(java.lang.String sex) {
		set("SEX", sex);
		return (M)this;
	}
	
	public java.lang.String getSex() {
		return getStr("SEX");
	}

	public M setAddr(java.lang.String addr) {
		set("ADDR", addr);
		return (M)this;
	}
	
	public java.lang.String getAddr() {
		return getStr("ADDR");
	}

	public M setTel(java.lang.String tel) {
		set("TEL", tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("TEL");
	}

	public M setPicpath(java.lang.String picpath) {
		set("PICPATH", picpath);
		return (M)this;
	}
	
	public java.lang.String getPicpath() {
		return getStr("PICPATH");
	}

	public M setBirty(java.util.Date birty) {
		set("BIRTY", birty);
		return (M)this;
	}
	
	public java.util.Date getBirty() {
		return get("BIRTY");
	}

	public M setFartherid(java.lang.Integer fartherid) {
		set("FARTHERID", fartherid);
		return (M)this;
	}
	
	public java.lang.Integer getFartherid() {
		return getInt("FARTHERID");
	}

	public M setMotherid(java.lang.Integer motherid) {
		set("MOTHERID", motherid);
		return (M)this;
	}
	
	public java.lang.Integer getMotherid() {
		return getInt("MOTHERID");
	}

	public M setRemark(java.lang.String remark) {
		set("REMARK", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("REMARK");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("CREATETIME", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("CREATETIME");
	}

	public M setBlood(java.lang.String blood) {
		set("BLOOD", blood);
		return (M)this;
	}
	
	public java.lang.String getBlood() {
		return getStr("BLOOD");
	}

}
