package zhrk.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQxPicLibrary<M extends BaseQxPicLibrary<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("ID", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public M setMisid(java.lang.Integer misid) {
		set("MISID", misid);
		return (M)this;
	}
	
	public java.lang.Integer getMisid() {
		return getInt("MISID");
	}

	public M setPicpath(java.lang.String picpath) {
		set("PICPATH", picpath);
		return (M)this;
	}
	
	public java.lang.String getPicpath() {
		return getStr("PICPATH");
	}

	public M setAddress(java.lang.String address) {
		set("ADDRESS", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("ADDRESS");
	}

	public M setCtime(java.util.Date ctime) {
		set("CTIME", ctime);
		return (M)this;
	}
	
	public java.util.Date getCtime() {
		return get("CTIME");
	}

	public M setUserid(java.lang.Integer userid) {
		set("USERID", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("USERID");
	}

}
