package zhrk.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQxMenu<M extends BaseQxMenu<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("ID", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public M setName(java.lang.String name) {
		set("NAME", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("NAME");
	}

	public M setPic(java.lang.String pic) {
		set("PIC", pic);
		return (M)this;
	}
	
	public java.lang.String getPic() {
		return getStr("PIC");
	}

	public M setPath(java.lang.String path) {
		set("PATH", path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("PATH");
	}

	public M setIstop(java.lang.Integer istop) {
		set("ISTOP", istop);
		return (M)this;
	}
	
	public java.lang.Integer getIstop() {
		return getInt("ISTOP");
	}

	public M setParid(java.lang.Integer parid) {
		set("PARID", parid);
		return (M)this;
	}
	
	public java.lang.Integer getParid() {
		return getInt("PARID");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("CREATETIME", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("CREATETIME");
	}

}
